### ISSUE TITLE
git.sh failed 

### ISSUE THREAD

**Issue by AEW2015** [Thales-RISC-V/TMR#2]
git.sh is referencing nonexistent commits of submodules. 

./git.sh 
### Init submodules ###
Submodule 'riscv-openocd' (https://github.com/Thales-RISC-V/riscv-openocd) registered for path 'riscv-openocd'
Submodule 'riscv-zephyr' (https://github.com/Thales-RISC-V/riscv-zephyr) registered for path 'riscv-zephyr'
Submodule 'thales-risc-v-chisel-project' (https://github.com/Thales-RISC-V/thales-risc-v-registers-router) registered for path 'thales-risc-v-chisel-project'
Submodule 'thales-risc-v-fault-detector' (https://github.com/Thales-RISC-V/thales-risc-v-fault-detector/) registered for path 'thales-risc-v-fault-detector'
Submodule 'thales-risc-v-jtag-router' (https://github.com/Thales-RISC-V/thales-risc-v-jtag-router/) registered for path 'thales-risc-v-jtag-router'
Submodule 'thales-risc-v-registers-router' (https://github.com/Thales-RISC-V/thales-risc-v-registers-router/) registered for path 'thales-risc-v-registers-router'
Submodule 'ultrascale-linux' (https://github.com/Thales-RISC-V/ultrascale-linux) registered for path 'ultrascale-linux'
Submodule 'ultrascale-u-boot' (https://github.com/Thales-RISC-V/ultrascale-u-boot) registered for path 'ultrascale-u-boot'
Cloning into '/home/sand/TMR/riscv-openocd'...
Cloning into '/home/sand/TMR/riscv-zephyr'...
Cloning into '/home/sand/TMR/thales-risc-v-chisel-project'...
Cloning into '/home/sand/TMR/thales-risc-v-fault-detector'...
Cloning into '/home/sand/TMR/thales-risc-v-jtag-router'...
Cloning into '/home/sand/TMR/thales-risc-v-registers-router'...
Cloning into '/home/sand/TMR/ultrascale-linux'...
Cloning into '/home/sand/TMR/ultrascale-u-boot'...
Submodule path 'riscv-openocd': checked out 'f7bd149fa85f6b3611ca54bb7021ea01d069b1e3'
Submodule path 'riscv-zephyr': checked out 'd236be82374687372da3f60899dfd10a4ff741ef'
error: Server does not allow request for unadvertised object a3f293b7c44a7e3749d63f0f1b29c16b3aa12c28
Fetched in submodule path 'thales-risc-v-chisel-project', but it did not contain a3f293b7c44a7e3749d63f0f1b29c16b3aa12c28. Direct fetching of that commit failed.
### submodules thales-risc-v-fault-detector ###
error: pathspec 'rocket-chip' did not match any file(s) known to git.
./git.sh: line 9: cd: rocket-chip: No such file or directory
error: pathspec 'firrtl' did not match any file(s) known to git.
error: pathspec 'chisel3' did not match any file(s) known to git.
error: pathspec 'torture' did not match any file(s) known to git.
error: pathspec 'hardfloat' did not match any file(s) known to git.
### submodules thales-risc-v-jtag-router ###
error: pathspec 'rocket-chip' did not match any file(s) known to git.
./git.sh: line 15: cd: rocket-chip: No such file or directory
error: pathspec 'firrtl' did not match any file(s) known to git.
error: pathspec 'chisel3' did not match any file(s) known to git.
error: pathspec 'torture' did not match any file(s) known to git.
error: pathspec 'hardfloat' did not match any file(s) known to git.
### submodules thales-risc-v-registers-router ###
error: pathspec 'rocket-chip' did not match any file(s) known to git.
./git.sh: line 21: cd: rocket-chip: No such file or directory
error: pathspec 'firrtl' did not match any file(s) known to git.
error: pathspec 'chisel3' did not match any file(s) known to git.
error: pathspec 'torture' did not match any file(s) known to git.
error: pathspec 'hardfloat' did not match any file(s) known to git.
### submodules thales-risc-v-chisel-project ###
error: pathspec 'testchipip' did not match any file(s) known to git.
error: pathspec 'rocket-chip/firrtl' did not match any file(s) known to git.
error: pathspec 'rocket-chip/chisel3' did not match any file(s) known to git.
error: pathspec 'rocket-chip/torture' did not match any file(s) known to git.
error: pathspec 'rocket-chip/hardfloat' did not match any file(s) known to git.

**Comment by ghost** [comment]
It was a mistake in the .gitmodules path. 
Thank you for reporting it.
